version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0 #3rd party orb of snyk
  heroku: circleci/heroku@2.0.0 #allows us to use heroku orbs's command

jobs:
  build:
    docker:
      - image: maven:3.8-jdk-17
    steps:
      - checkout
      - run: mvn clean install

  test:
    docker:
      - image: maven:3.8-jdk-17
    steps:
      - checkout
      - run: mvn test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: limzihan/education-space
          tag: <<pipeline.git.tag>>
      - docker/push:
          image: limzihan/education-space
          tag: <<pipeline.git.tag>>

  scan:
    docker:
      - image: maven:3.6.3
    environment:
      IMAGE_NAME: limzihan/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

  deploy:
    docker:
      - image: maven:3.8-jdk-17
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a limzihan-su-devops
            heroku container:release web -a limzihan-su-devops

workflows:
  ci-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop
      - scan:
          requires:
            - build

  cicd-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
          filters:
            branches:
              only: release
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: release
            tags:
              only: /^v./
      - scan:
          requires:
            - build
      - deploy:
          requires:
            - build-and-push
